export const skills = [
  'Python (2.x, 3.x)',
  'Kubernetes',
  'Docker',
  'Cloud Security',
  'DevSecOps',
  'Microservices',
  'System Design',
  'AWS Services',
  'PostgreSQL',
  'FastAPI',
  'Django',
  'Flask',
  'GoLang',
  'NodeJS',
  'React',
  'CI/CD',
  'Jenkins',
  'GitLab CI',
  'GitHub Actions',
  'Terraform',
  'CSPM',
  'CNAPP',
  'RBAC',
  'Redis',
  'Gurobi',
  'Team Leadership',
  'Code Review',
  'Mentorship'
];

export const achievements = [
  'Led team of 8+ engineers in successful cloud migration project',
  'Architected 15+ microservices handling 100+ countries for Fortune 500 company (Reckitt)',
  'Built CSPM solution securing Kubernetes clusters and cloud accounts',
  'Implemented automated testing framework increasing code coverage by 60%',
  'Designed ETL pipelines handling multi-TB datasets with zero-downtime migrations',
  'Resolved critical production issues ensuring global uptime for enterprise systems',
  'Integrated CNAPP/CSPM security into CI/CD pipelines',
  'Developed financial forecasting systems handling 500,000+ record datasets',
  'Recognized as Top Performer for 3 consecutive years',
  'AWS Certified Solutions Architect',
  'Kubernetes (CKAD) Certified',
];
